### ISSUE TITLE
The `add-path` command is deprecated and will be disabled soon.

### ISSUE THREAD

**Issue by jlesage** [mig4/setup-bats#11]
Using this action generates the following warning:

> The `add-path` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

**Comment by mig4** [comment]
I've just published [v1.0.2](https://github.com/mig4/setup-bats/releases/tag/v1.0.2) which addresses this. Many thanks for reporting @jlesage :heart:
